version: '3.3'
services:

 mysql:
   image: mysql:5.7
   container_name: 'mysql'
   labels:
      conteiner.description: "Mysql 5.7 DB"
   ports:
      - 3306:3306
   volumes:
      - ./mysqldata:/var/lib/mysql
      - ./conf/mysqld.cnf://etc/mysql/mysql.conf.d/mysqld.cnf:ro
   restart: always
   environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=glpihml
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpiuser
      - MYSQL_PASSWORD=glpipass

 glpi:
   build:
     context: .
     dockerfile: Dockerfile-glpi
     args:
       UBUNTU_VERSION: 16.04
   container_name: 'glpi'
   depends_on:
     - mysql
   labels:
      conteiner.description: "GLPI Web Server Apache"
   volumes:
     - ./html:/var/www/html
     - ./scripts/glpi-start.sh:/opt/glpi-start.sh:ro
   restart: always
   ports:
     - 80:80
     - 443:443
   environment:
     - GLPI_VERSION=9.1.3
     - GLPI_MYSQL_HOST=mysql
     - GLPI_MYSQL_USER=glpiuser
     - GLPI_MYSQL_PASS=glpipass
     - GLPI_MYSQL_DB=glpi

 phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   container_name: 'phpmyadmin'
   labels:
      conteiner.description: "PHPmyadmin Webpage"
   ports:
      - 8080:80
   volumes:
      - /sessions
   restart: always
   environment:
      - TZ=America/Sao_Paulo
      - PMA_HOST=mysql
      - PMA_PORT=3306


